### ISSUE TITLE
[New content type request] Shell code is generic detect POSIX, sh, bash, zsh, fish etc

### ISSUE THREAD

**Issue by andrewcrook** [google/magika#182]
List here
https://en.wikipedia.org/wiki/Comparison_of_command_shells

**Comment by reyammer** [comment]
Thanks for reporting. This feels a bit finer-grained than we would like go with in the immediate future. The current goal is to be of support for automated workflows for file scanning, and I would assume that these workflows would treat all these variants in the same way. I'm closing this one but keep the tag on, so that we can consider it for the future. Please reopen if you would have a specific use case for this, thanks!
