### ISSUE TITLE
[Misdetection] Password protected Microsoft Excel 2007+ document (.xlsx) misdetected as MS Outlook Message (application)

### ISSUE THREAD

**Issue by bjester** [google/magika#258]
**What should the file have been detected as? What has the file been misdetected as?**
A MS Excel 2007+ (.xlsx) spreadsheet that has been protected with a password is not accurately identified-- with low confidence it was dected as an MS Outlook Message.

**Please link or attach the misdetected file below** (Do NOT upload PII!)
[password-protected-example.xlsx](https://github.com/google/magika/files/14398943/password-protected-example.xlsx)

Or:
1) Open LibreOffice spreadsheet application
2) Create a MS Excel 2007+ spreadsheet with .xlsx extension
3) Click _File > Save as... > Save with password_
4) Set password
5) Save

**Additional context**
Both the attached file and an existing private, password-protected, file were detected the same-- MS Outlook Message

```
$ magika -r -m high-confidence ~/Downloads/password-protected-example.xlsx 
/home/bjester/Downloads/password-protected-example.xlsx: Unknown binary data (unknown) [Low-confidence model best-guess: MS Outlook Message (application), score=62]
$ mimetype ~/Downloads/password-protected-example.xlsx 
/home/bjester/Downloads/password-protected-example.xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

```

**Comment by reyammer** [comment]
Thanks for reporting (and sorry for the long delay). This indeed seems a tricky sample. We have a new model, and that says `Word CDF`, which is still not correct. Unfortunately magika currently doesn't support encrypted files of this kind. That being said, it's unclear why `mimetype` says `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`; `file` says `CDFV2 Encrypted` / `application/encrypted`. I quickly checked the header, and it does look like a CDF, rather than a OOXML. (So the extension should likely be `.xls`, not `.xlsx`)? CC @corkamig 

Anyways, for now added to our set of problematic samples so that we can try to improve for the future (CLA: checked).

Thanks again!

**Comment by corkamig** [comment]
Indeed, it's a CDF, but it's internally an 'Encrypted Package'. The binary content doesn't show that it's an Excel, Word or whatever.
