### ISSUE TITLE
Add support for 3.12 python

### ISSUE THREAD

**Issue by paul-nameless** [google/magika#43]
Is there any reason that prevents it from running on 3.12 python?

BTW amazing job, great library!

**Comment by reyammer** [comment]
Thank you!

/CC @invernizzi @ebursztein

I briefly checked this in the past, and we were running into problems with numpy. I now checked better.

It turns out that recent versions of numpy (>=1.26.0) support well python 3.12. However, these versions require python >=3.9.

The current version of numpy we use is 1.24.4, which supports python >= 3.8, <=3.11 (actually, it declares support for >=3.8, but it does not specify <=3.11).

The current magika package declares support for >=3.8,<=3.11.

This is a working version for python 3.12: https://github.com/google/magika/tree/support-python-3.12

We are now a bit stuck: if we bump the numpy version we use, we need to drop support for python 3.8. If we don't bump it, then we can't support 3.12.

Any expert in the room that knows how to deal with this? Is there some poetry trick to specify dependencies versions that depend on which python version one is targeting (eg: if you have python 3.8, then install X; if you have python 3.12 then install Y)? Is the only way to deal with this to publish a new version and drop support for python 3.8?

According to [this](https://www.python.org/downloads/release/python-3817/#:~:text=According%20to%20the%20release%20calendar,only%20form%20until%20October%202024.), python 3.8 is out of support, so we may actually want to drop support as well.

Thoughts?

**Comment by TheMythologist** [comment]
In my opinion, I don't see a point supporting python 3.8 since it is out of support already. If there are projects that still use python 3.8, they could stick to the current version of magika, and we'll remove 3.8 support in the next magika version

**Comment by dbohdan** [comment]
According to that link and <https://devguide.python.org/versions/>, Python 3.8 will receive support in the form of irregular source-only security releases until October 2024. So it is still not EOL.

From my perspective, support for Python 3.12 is more important than support for soon-to-be-EOL Python 3.8. To give an example, I have a project where I have not merged a branch replacing python-magic with Magika because the project normally runs in Python 3.12. I also install Python applications with pipx and Python 3.12, but I can't install the Magika CLI in my default way. I would prefer dropping 3.8 for 3.12.

**Comment by jfcherng** [comment]
So it looks like magika can be run on both 3.8 and 3.12 but they require different version of numpy. And that just can't be done in a .lock file?

**Comment by reyammer** [comment]
I'm checking PR #148 by @TheMythologist and it seems there is indeed a way to specify alternatives... this would solve all the problems! If that works, we'll try to merge already today.

**Comment by reyammer** [comment]
I confirm that this is now fixed by #148 and tests seem to pass from python 3.8 to python 3.12! 🥳

**Comment by reyammer** [comment]
Following up on this: pushed to pypi magika 0.5.1, which now supports >=3.8, <3.13!
