### ISSUE TITLE
Thresholds

### ISSUE THREAD

**Issue by yaniv5678** [google/magika#592]
Hi,

In the rust code, I see that `lib/src/model.rs` contains a thresholds array of 1/2's in the `ModelConfig` struct.
I've also seen there's a `thresholds.json` file only for model v1, but not for model v2 which is the currently used model in the rust lib.
While debugging the code, I saw that the thresholds stay with default values (1/2s).
Is it possible to support the real v2 thresholds (if such exist) such that when I use the rust lib it will check whether the classification is in the right threshold?

Will there any `thresholds.json` for v2?
Will you run on it `rust/gen/src/main.rs` before publishing the crate such that the `model.rs` file will be right and not contain default values?

Thanks.

**Comment by ia0** [comment]
> I've also seen there's a `thresholds.json` file only for model v1, but not for model v2 which is the currently used model in the rust lib.

The model v2 (more precisely `draft_standard_v2` in our case) has all model configuration under a single file (namely `config.min.json`) instead of multiple files (including a `thresholds.json` file). If you look attentively, you will see that at the end of this configuration file there is `"thresholds": {}` meaning that no thresholds are used, which is semantically equivalent to using the medium confidence threshold defined in that same file as `"medium_confidence_threshold": 0.5`.

> Is it possible to support the real v2 thresholds (if such exist) such that when I use the rust lib it will check whether the classification is in the right threshold?

Yes. This was tracked by #549 and fixed by #555. This is now the behavior at head.

> Will there any `thresholds.json` for v2?

As issues will be discovered, I expect the `config.min.json` to update the value of its `thresholds` field. The model is still too young for that (and not even published).

> Will you run on it `rust/gen/src/main.rs` before publishing the crate such that the `model.rs` file will be right and not contain default values?

The Rust CI triggers (among other things) when the models or their configuration are modified. So whenever thresholds are modified (e.g. by adding a threshold for a specific content type), then the CI will fail and the author of the PR will follow the instructions of the failed test, namely:

https://github.com/google/magika/blob/cbc2cb861b7b54ee7c9a6dfff3fa23ecf94a6007/rust/sync.sh#L23

I hope this fixes the issue and answers all your questions. Feel free to reopen the issue otherwise.
