### ISSUE TITLE
Could you tell me what's the meaning of `magic` and `vt_type`?

### ISSUE THREAD

**Issue by amone-bit** [google/magika#833]
![Image](https://github.com/user-attachments/assets/1443abda-cd35-4cfa-b9ff-5315762404b4)

**Comment by reyammer** [comment]
About `group` and other metadata: that json contains entries for many more content types that we actually support (and for many of them we don't / didn't have proper metadata), but we (should) have proper metadata for any supported by the model v1. That json is not really part of the API and should not be rely upon (and it has in fact been refactored in the new version).

About reopening issues: it turns out it's a "feature" from github, you can only reopen if you are a collaborator or if you closed the issue yourself (ref: https://github.com/orgs/community/discussions/41926#discussioncomment-6975082). I reopened it now, feel free to follow up or close it if all answers are clear.

Thanks!
